version: '3.7'

services:

    registry:
        image: registry-service
        container_name: registry-container
        mem_limit: 768m
        ports:
            - "8761:8761"
        networks:
            - currency-network

    currency-conversion:
        image: currency-conversion-service
        container_name: currency-conversion-container
        mem_limit: 768m
        ports:
            - "8100:8100"
        networks:
            - currency-network
        depends_on:
            -   registry
        environment:
            -   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://admin:admin1234@registry:8761/services/registry/eureka

networks:
    currency-network: